language: python
python:
    - "2.7"
sudo: false

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -f -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH

env:
    - DJANGO_VERSION=1.11.7

script:
    - conda update -q conda --yes
    - conda create -n test_env python=2 django=1.11.7 gdal mock nansat pythesint -c conda-forge --yes
    - source activate test_env
    - pip install https://github.com/ghaering/pysqlite/archive/2.8.1.tar.gz
    - python setup.py install
    - python runtests.py

